'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/hooks/contexts/auth-context';
import { data } from '@/lib/data-client';
import { Sparkles, Loader2, Info } from 'lucide-react';

interface SummarySectionProps {
  /** Which table the document lives in. */
  target: 'version' | 'report';
  /** The bill_versions.id or committee_reports.id being summarized. */
  documentId: string;
  /** Existing saved AI summary, if any. Rendered directly when present. */
  existingSummary?: string | null;
  /** Word for the source in copy, e.g. "version" or "committee report". */
  noun?: string;
}

type State =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'done'; summary: string; model: string | null }
  | { status: 'error'; message: string };

/**
 * Per-item AI summary. Resolves in priority order:
 *  1. AI opted out → verbiage pointing to the View button to read the source.
 *     This outranks everything else: with the toggle off we show no AI summary
 *     at all, not even one already saved on the row or generated earlier this
 *     session. Opting out is about what the user sees, not just what we infer.
 *  2. A saved `existingSummary` (or one generated just now) → render it.
 *  3. AI opted in, no summary → a "Summarize" button.
 *
 * The opt-in check here is a UI courtesy only — the server re-checks it before
 * any inference (see actions/summaries.ts).
 */
export function SummarySection({
  target,
  documentId,
  existingSummary,
  noun = 'document',
}: SummarySectionProps) {
  const { preferences } = useAuth();
  const aiOptedIn = preferences?.ai_opt_in === true;

  const [state, setState] = useState<State>({ status: 'idle' });

  // Checked before any summary is read so toggling AI off hides one that is
  // already on screen, rather than only suppressing the next generation.
  if (!aiOptedIn) {
    return (
      <div className="flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
        <span>AI summaries are off. Open the {noun} to read it in full.</span>
      </div>
    );
  }

  // Derived, not seeded into state: `existingSummary` can arrive after mount
  // once the panel's fetch resolves.
  if (state.status === 'done') {
    return <SummaryCard summary={state.summary} model={state.model} />;
  }

  if (existingSummary) {
    return <SummaryCard summary={existingSummary} model={null} />;
  }

  async function summarize() {
    setState({ status: 'loading' });
    try {
      const result = await data.summaries.summarizeDocument({ target, id: documentId });
      setState({ status: 'done', summary: result.summary, model: result.model });
    } catch (error: any) {
      setState({ status: 'error', message: error?.message || "Couldn't summarize — try again." });
    }
  }

  return (
    <div className="flex flex-col gap-1">
      <Button
        variant="ghost"
        size="sm"
        onClick={summarize}
        disabled={state.status === 'loading'}
        className="h-7 gap-1 self-start px-1.5 text-xs text-olive-dark hover:bg-transparent hover:text-olive-dark/80 focus-visible:bg-transparent"
      >
        {state.status === 'loading' ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
        {state.status === 'loading' ? 'Summarizing…' : 'Summarize'}
      </Button>
      {state.status === 'error' && (
        <span className="px-1.5 text-[11px] text-destructive">{state.message}</span>
      )}
    </div>
  );
}

export function SummaryCard({ summary, model }: { summary: string; model: string | null }) {
  return (
    <div className="rounded-md border border-olive-dark/30 bg-olive-soft/40 p-2.5">
      <div className="mb-1 flex items-center gap-1.5">
        <Sparkles className="h-3 w-3 text-olive-dark" />
        <span className="text-[10px] font-semibold uppercase tracking-wider text-olive-dark">AI summary</span>
      </div>
      <p className="text-[11px] leading-relaxed text-foreground/80">{summary}</p>
      {/* {model && (
        <p className="mt-1.5 text-[10px] text-muted-foreground">Generated by {model}</p>
      )} */}
      <p className="mt-2 flex items-start gap-1 border-t border-olive-dark/20 pt-1.5 text-[10px] leading-snug text-muted-foreground">
        <Info className="mt-px h-3 w-3 shrink-0" aria-hidden="true" />
        <span>
          This summary is AI-generated and may be incomplete or wrong. Always read the official document before
          relying on it or testifying.
        </span>
      </p>
    </div>
  );
}
